# Generated by Django 6.1 on 2026-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ratshie (Pty) Ltd', max_length=120)),
                ('tagline', models.CharField(default='Vehicle repairs, diagnostics & mobile spares delivery in the Northern Cape', max_length=200)),
                ('phone', models.CharField(default='+27614884254', max_length=32)),
                ('phone_display', models.CharField(default='061 488 4254', max_length=32)),
                ('whatsapp_number', models.CharField(default='27659017566', max_length=32)),
                ('whatsapp_display', models.CharField(default='065 901 7566', max_length=32)),
                ('email', models.EmailField(default='livhuwaniratshibvumo7@gmail.com', max_length=254)),
                ('contact_name', models.CharField(default='Livhuwani', max_length=120)),
                ('address', models.CharField(default='Seoding Village, Kuruman, Northern Cape, South Africa', max_length=255)),
                ('service_radius_km', models.PositiveIntegerField(default=50)),
                ('hero_headline', models.CharField(default='Expert Automotive Care', max_length=160)),
                ('hero_statement', models.TextField(default='Professional vehicle servicing, diagnostics, repairs and quality automotive products you can trust.')),
                ('about_short', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('vehicle', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Star rating out of 5.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
