# Generated by Django 6.1 on 2026-08-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(blank=True, max_length=60)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('enquiry_type', models.CharField(choices=[('general', 'General Enquiry'), ('service', 'Service'), ('repair', 'Repair'), ('diagnostic', 'Diagnostic'), ('product', 'Product'), ('spare_part', 'Spare Part'), ('lubricant', 'Lubricant'), ('quote', 'Quote')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
