# Generated by Django 6.1 on 2026-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Public holiday',
                'verbose_name_plural': 'Public holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='standard_delivery_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of business days (Mon-Fri) for standard delivery estimates.', verbose_name='Standard delivery (business days)'),
        ),
    ]
