# Generated by Django 6.1 on 2026-09-22 19:16

from django.db import migrations, models


def update_stored_business_email(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(email="livhuwaniratshibvumo7@gmail.com").update(
        email="admin@ratshie.co.za"
    )


def restore_stored_business_email(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(email="admin@ratshie.co.za").update(
        email="livhuwaniratshibvumo7@gmail.com"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicholiday_siteconfig_standard_delivery_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(default='admin@ratshie.co.za', max_length=254),
        ),
        migrations.RunPython(
            update_stored_business_email,
            restore_stored_business_email,
        ),
    ]
