# Generated by Django 6.1 on 2026-10-02 06:03

from django.db import migrations, models


def update_stored_business_phone(apps, schema_editor):
    """Point the singleton's stored contact number at the current business line.

    Field defaults only affect new rows, so the existing pk=1 row keeps the
    number it was created with. Every template renders cfg.phone_display, so
    without this the old number stays on the live site after deploying.
    """
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(phone="+27614884254").update(phone="+27614884252")
    SiteConfig.objects.filter(phone_display="061 488 4254").update(
        phone_display="061 488 4252"
    )


def restore_stored_business_phone(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(phone="+27614884252").update(phone="+27614884254")
    SiteConfig.objects.filter(phone_display="061 488 4252").update(
        phone_display="061 488 4254"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfig_email_admin_ratshie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.CharField(default='+27614884252', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_display',
            field=models.CharField(default='061 488 4252', max_length=32),
        ),
        migrations.RunPython(
            update_stored_business_phone,
            restore_stored_business_phone,
        ),
    ]
