# Generated by Django 6.1 on 2026-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Name of an inline SVG icon (see templates for available keys).', max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_on_request', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
