# Generated by Django 6.1 on 2026-10-02 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +27 61 488 4252.', regex='^\\+?[0-9\\s\\-()]{7,20}$')]),
        ),
    ]
