# Generated by Django 6.1 on 2026-09-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
        ('orders', '0002_remove_order_needs_delivery_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_estimate_from',
            field=models.DateField(blank=True, help_text='Calculated delivery start date (business days).', null=True, verbose_name='Delivery estimate from'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_estimate_source',
            field=models.CharField(default='product', help_text='Whether estimate came from product settings or admin override.', max_length=20, verbose_name='Estimate source'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_estimate_to',
            field=models.DateField(blank=True, help_text='Calculated delivery end date (business days).', null=True, verbose_name='Delivery estimate to'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_estimate_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimate updated at'),
        ),
        migrations.CreateModel(
            name='OrderDeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_from', models.DateField(blank=True, null=True)),
                ('previous_to', models.DateField(blank=True, null=True)),
                ('new_from', models.DateField(blank=True, null=True)),
                ('new_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_email', models.BooleanField(default=False)),
                ('notified_sms', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery history',
                'verbose_name_plural': 'Delivery history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('confirmation', 'Order confirmation'), ('delivery_update', 'Delivery update')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('status', models.CharField(default='sent', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order notification',
                'verbose_name_plural': 'Order notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
