# Generated by Django 6.1 on 2026-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_estimate_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_estimate_source',
            field=models.CharField(choices=[('product', 'Product settings'), ('admin_override', 'Admin override')], default='product', help_text='Whether estimate came from product settings or admin override.', max_length=20, verbose_name='Estimate source'),
        ),
    ]
