# Generated by Django 6.1 on 2026-09-23 01:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_estimate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_enabled', models.BooleanField(default=True, verbose_name='Standard Delivery available')),
                ('standard_fee', models.DecimalField(decimal_places=2, default=Decimal('99.00'), help_text="Flat fee charged for standard delivery to the customer's address.", max_digits=10, verbose_name='Standard Delivery fee (R)')),
                ('free_enabled', models.BooleanField(default=True, verbose_name='Free Delivery available')),
                ('free_minimum', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Orders with a total at or above this amount (before shipping) qualify for free delivery.', max_digits=10, verbose_name='Free Delivery minimum order (R)')),
                ('pickup_enabled', models.BooleanField(default=True, verbose_name='Local Pickup available')),
                ('pickup_location', models.CharField(default='Kuruman, Northern Cape', help_text='Where customers can collect their order.', max_length=255, verbose_name='Pickup location')),
                ('pickup_instructions', models.TextField(blank=True, help_text='Optional notes shown to customers who choose local pickup.', verbose_name='Pickup instructions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping settings',
                'verbose_name_plural': 'Shipping settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Delivery'), ('free', 'Free Delivery'), ('pickup', 'Local Pickup')], default='', help_text="Shipping method chosen at checkout; snapshot of the customer's choice.", max_length=20, verbose_name='Shipping method'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_label',
            field=models.CharField(blank=True, default='', help_text='Human-friendly name of the shipping method, captured at checkout.', max_length=60, verbose_name='Shipping method label'),
        ),
    ]
