# Generated by Django 6.1 on 2026-10-01 05:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_shippingsettings_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='free_enabled',
            field=models.BooleanField(default=True, help_text="When enabled, an order total at or above the minimum below is delivered free. This is applied automatically to Standard Delivery - the customer is never given a separate 'free delivery' choice.", verbose_name='Offer free delivery over a minimum order value'),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='free_minimum',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Orders with a total at or above this amount (before shipping) get Standard Delivery free, applied automatically. Below this amount the standard fee is charged and checkout shows how much more is needed to qualify.', max_digits=10, verbose_name='Free Delivery minimum order (R)'),
        ),
    ]
