# Generated by Django 6.1 on 2026-10-01 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_shippingsettings_free_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingsettings',
            name='big_item_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), help_text="Delivery charge applied to products marked 'Big item'. Charged once per order, not per item.", max_digits=10, verbose_name='Big item delivery fee (R)'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='big_item_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text="Reference value only. It flags a product as worth reviewing for big-item handling, but it never changes a charge on its own - a product is only charged the big item fee when the admin explicitly sets its Delivery type to 'Big item'.", max_digits=10, verbose_name='Big item reference value (R)'),
        ),
    ]
