# Generated by Django 6.1 on 2026-10-01 07:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shippingsettings_big_item_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='free_enabled',
            field=models.BooleanField(default=True, help_text="When enabled, an order of small items at or above the minimum below is delivered free. This is applied automatically to Standard Delivery - the customer is never given a separate 'free delivery' choice. Large item delivery fees are not waived by this.", verbose_name='Offer free delivery over a minimum order value'),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='free_minimum',
            field=models.DecimalField(decimal_places=2, default=Decimal('800.00'), help_text='Small-item orders with a total at or above this amount (before shipping) get Standard Delivery free, applied automatically. Below this amount the standard fee is charged and checkout shows how much more is needed to qualify. This does not apply to large item delivery, which is always charged at its own fee.', max_digits=10, verbose_name='Small items free delivery minimum (R)'),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='standard_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text="Flat fee charged for standard delivery to the customer's address.", max_digits=10, verbose_name='Standard Delivery fee (R)'),
        ),
    ]
