# Generated by Django 6.1 on 2026-10-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_shippingsettings_free_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text="Recorded at checkout when the customer ticked the terms checkbox. Kept for the order's audit trail; existing orders stay False.", verbose_name='Terms & Conditions accepted'),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Server timestamp of the acceptance. Not client-supplied.', null=True, verbose_name='Terms accepted at'),
        ),
    ]
