# Generated by Django 6.1 on 2026-10-09 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_terms_acceptance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingsettings',
            options={'verbose_name': 'Delivery settings', 'verbose_name_plural': 'Delivery settings'},
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='big_item_fee',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='big_item_threshold',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='free_enabled',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='free_minimum',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='pickup_enabled',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='pickup_instructions',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='standard_enabled',
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='standard_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Flat fee charged on every delivery order.', max_digits=10, verbose_name='Delivery fee (R)'),
        ),
    ]
