# Generated by Django 6.1 on 2026-10-10 14:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_shippingsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='standard_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Standard fee for products set to use standard delivery.', max_digits=10, verbose_name='Delivery fee (R)'),
        ),
    ]
