# Generated by Django 6.1 on 2026-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_shippingsettings_standard_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text="Set automatically when the confirmed payment deducts this order's stock. Guarantees a duplicate payment notification cannot deduct the same units twice.", verbose_name='Stock deducted'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, help_text='Server timestamp of the stock deduction. Not client-supplied.', null=True, verbose_name='Stock deducted at'),
        ),
    ]
