# Generated by Django 6.1 on 2026-08-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(choices=[('service', 'Service quote'), ('product', 'Product quote')], default='service', max_length=20)),
                ('vehicle_make', models.CharField(blank=True, max_length=60)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('registration', models.CharField(blank=True, max_length=30)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('service_name', models.CharField(blank=True, max_length=120)),
                ('product_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('attachment', models.FileField(blank=True, upload_to='quote_attachments/')),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('declined', 'Declined'), ('closed', 'Closed')], default='new', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
