# Generated by Django 6.1 on 2026-08-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product_categories/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='SKU / Part number')),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of extra image paths.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_on_request', models.BooleanField(default=True)),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('limited', 'Limited Stock'), ('backorder', 'Backorder'), ('on_request', 'On Request'), ('out_of_stock', 'Out of Stock')], default='on_request', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('vehicle_makes', models.CharField(blank=True, help_text='Comma-separated makes.', max_length=200)),
                ('vehicle_models', models.CharField(blank=True, max_length=200)),
                ('viscosity', models.CharField(blank=True, max_length=40)),
                ('volume', models.CharField(blank=True, max_length=40)),
                ('oil_type', models.CharField(blank=True, max_length=60)),
                ('spec', models.CharField(blank=True, max_length=160, verbose_name='API / specification')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_genuine', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=160)),
                ('vehicle_make', models.CharField(blank=True, max_length=60)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('registration', models.CharField(blank=True, max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('quoted', 'Quoted'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_enquiries', to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
