# Generated by Django 6.1 on 2026-08-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set higher than the current price to show the product ON SALE (with a struck-through original price and dynamically-calculated discount).', max_digits=10, null=True, verbose_name='Original price'),
        ),
    ]
