# Generated by Django 6.1 on 2026-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_gallery_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_source',
            field=models.CharField(blank=True, help_text='Administrative metadata: where this image came from (e.g. manufacturer site, Wikimedia Commons). Not shown to customers.', max_length=300, verbose_name='Source'),
        ),
    ]
