# Generated by Django 6.1 on 2026-08-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link back to the original page the image was sourced from. Not shown to customers.', max_length=500, verbose_name='Source page URL'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Only VERIFIED images are shown to the public.', max_length=20, verbose_name='Verification status'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Private admin notes about how this image was checked.', verbose_name='Verification notes'),
        ),
    ]
