# Generated by Django 6.1 on 2026-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_source_url_productimage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_member_only',
            field=models.BooleanField(default=False, help_text='When enabled, only registered, authenticated members may purchase this product. Anonymous visitors can still view it and its price, but cannot add it to the cart or buy it. On-sale products should normally be member-only so every visitor sees the deal but only members can buy.', verbose_name='Member-only purchase'),
        ),
    ]
