# Generated by Django 6.1 on 2026-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_member_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_date_from',
            field=models.DateField(blank=True, help_text="Specific delivery date (used when Delivery mode is 'Specific date').", null=True, verbose_name='Delivery date from'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_date_to',
            field=models.DateField(blank=True, help_text="End of delivery range (used when Delivery mode is 'Date range').", null=True, verbose_name='Delivery date to'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_mode',
            field=models.CharField(choices=[('standard', 'Use standard delivery'), ('specific', 'Specific delivery date'), ('range', 'Delivery date range')], default='standard', help_text='Select how delivery time is determined for this product.', max_length=20, verbose_name='Delivery mode'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Short plain-language description of the image (used by screen readers and search engines).', max_length=160, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Main product image (the one shown as the product thumbnail).'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Image 0 is shown first on the product page.', verbose_name='Sort order'),
        ),
    ]
