# Generated by Django 6.1 on 2026-10-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productgroup_product_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Only used when Delivery type is 'Custom delivery fee'.", max_digits=10, null=True, verbose_name='Delivery fee (R)'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('standard', 'Standard delivery'), ('free', 'Free delivery'), ('custom', 'Custom delivery fee'), ('big_item', 'Big item')], default='standard', help_text='How this product is charged for delivery. Standard, Free and Big Item use the global rates in Orders > Shipping settings; Custom uses the fee below.', max_length=20, verbose_name='Delivery type'),
        ),
    ]
