# Generated by Django 6.1 on 2026-10-08 21:43

import secrets

from django.db import migrations, models


_SKU_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def _make_sku():
    return "RAT-" + "".join(secrets.choice(_SKU_ALPHABET) for _ in range(6))


def backfill_skus(apps, schema_editor):
    """Give every product a unique, non-blank SKU ahead of the unique index.

    Non-blank SKUs already in use are preserved. Only blank SKUs and exact
    duplicates are regenerated, so the new unique constraint can be applied.
    """
    Product = apps.get_model("products", "Product")
    seen = set()
    for product in Product.objects.order_by("pk").iterator():
        current = (product.sku or "").strip()
        if current and current not in seen:
            seen.add(current)
            continue
        candidate = _make_sku()
        while candidate in seen:
            candidate = _make_sku()
        seen.add(candidate)
        product.sku = candidate
        product.save(update_fields=["sku"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_delivery_fee_product_delivery_type'),
    ]

    operations = [
        migrations.RunPython(backfill_skus, noop),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate (e.g. RAT-4K7P2M). Stable once assigned.', max_length=80, unique=True, verbose_name='SKU / Part number'),
        ),
    ]