# Generated by Django 6.1 on 2026-10-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_type',
        ),
    ]
