# Generated by Django 6.1 on 2026-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Only used when 'Custom delivery fee' is selected. Enter 0.00 for free delivery on this product.", max_digits=10, null=True, verbose_name='Custom delivery fee (R)'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('standard', 'Use standard delivery fee'), ('custom', 'Custom delivery fee')], default='standard', help_text="How this product is charged for delivery at checkout. 'Use standard delivery fee' uses the global fee in Orders > Delivery settings; 'Custom delivery fee' uses the fee below.", max_length=20, verbose_name='Delivery fee'),
        ),
    ]
