# Generated by Django 6.1 on 2026-10-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_sync_stock_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text="How many units you physically have. This is the source of truth: 10 or more shows no warning badge, 1–9 shows 'Limited Stock', and 0 shows 'Out of Stock' and blocks purchase. The badge is automatic and is never selected by hand.", verbose_name='Stock quantity'),
        ),
    ]
